### PR TITLE
Fix oneOf responses

### PR DESCRIPTION
**Pull request by fabianrbz**
Related https://github.com/Nexmo/nexmo-developer/issues/1743

This changes the way we display the oneOf responses. 
It creates one table for each response with the corresponding attributes and toggles them depending on the Response selected.

### CODE REVIEW

**Comment by lornajane** [comment]
This does what I expected but I only seem to be able to select between responses in the right hand pane, the list of response fields just tells me which response is currently being shown - but no way to switch. We also discussed that I should add a field to make better labels than "Response 1" but I don't remember which field was to be used. Prompt me and I'll make some changes in the API specs.

**Comment by fabianrbz** [comment]
@lornajane the field we talked about was `description`

**Comment by fabianrbz** [comment]
@lornajane can you take another look? Sadly Volta's tabs don't support accessibility features :/, let me know if it's easier now, otherwise I'll look into adding support for it in Volta.

**Comment by lornajane** [comment]
This looks a lot better although the JSON/XML label can sort of float randomly depending where you are when you scroll. Can we possibly make those tabs clickable? Upstream contribution of that I know will be gratefully received as they are working more on accessibility. I also added some descriptions to the Verify API (and tagged you @fabianrbz to review) to try it out and it looks GREAT :smile:

**Comment by mheap** [comment]
tabindex=0 is enough to make them clickable. Sadly this can’t really be
contributed upstream as it’s a HTML structure thing rather than in the CSS,
so will be different for every app depending on if they use tabindex for
correctly (we only use it for focusing)

**Comment by fabianrbz** [comment]
@mheap @lornajane what about http://volta-core.vonage.com/storybook/?path=/story/layout-tabs--unstyled ?
I used the default one, and tried to add all the necessary accessibility features, but Volta's js doesn't support it and it also keeps a state for some reason.

What we could push upstream is the support for the aria controls and tabindexing, it is pure html + some js and it's up to the end user to add them

**Comment by mheap** [comment]
I'd keep the existing style rather than moving to unstyled. I believe that the structure is the same, it's purely CSS differences.

If we can push aria controls upstream in to the examples that would be excellent

**Comment by mheap** [comment]
@fabianrbz What do we need to get this merged?

**Comment by fabianrbz** [comment]
@mheap I'm currently working on the accessibility features in Volta, but we can merge this as it is and later bump the library

**Pull request merged**
